### ISSUE TITLE
关于Pnet的训练数据的问题

### ISSUE THREAD

**Issue by ccpocker** [LeslieZhoa/tensorflow-MTCNN#1]
请问一下，产生P-net的训练数据时。所有的postive,part的偏移量值是否都在-1到1之间。而landmark的偏移量值是否都在0到1之间？

**Comment by LeslieZhoa** [comment]
@ccpocker 你好，很抱歉才看到你的问题，对于positive和part的图像由于都是从原图截取的所以它的偏移量取值和iou的阈值选取有很大关系，我不是太肯定我的程序里的偏移量是否都在[-1,1]上，您可以写个if语句判断一下；对于landmark偏移量，如果您的图像未经过裁剪那么值一定在[0,1]之间的。希望可以帮助到您！

**Comment by ccpocker** [comment]
@LeslieZhoa  您好，非常感谢你能回答我的问题。对于postive和part的图像，如果偏移量超过[-1,1]上的话。那么训练的模型也可能会产生超过[-1,1]范围的偏移量。而根据Detector.py中的def calibrate_box代码，那么有可能会导致box框的左上角坐标与右下角坐标出现问题（例如左上角的x坐标比右下角的x坐标大之类的情况）。不知道您是否出现过这个问题，或者对这种问题进行了限制。

**Comment by LeslieZhoa** [comment]
Hi @ccpocker ,如果偏移量reg[2:]>reg[:2]，那么就应该不会出现您说的情况。我的训练和测试过程中没有出现这种问题,很抱歉不能给你什么更好的建议。
