### ISSUE TITLE
训练标签

### ISSUE THREAD

**Issue by chenwuxing** [LeslieZhoa/tensorflow-MTCNN#4]
作者你好，我想问下有关训练标签的问题。我自己制作的小的数据集已经标记完成，也已经做好对应的txt文件。
![s1](https://user-images.githubusercontent.com/41286936/54403698-fb6dcc00-470b-11e9-912f-bed8df18381a.png)
但是看到在data文件下wider face的训练标签文件有两个。
![TIM截图20190315101210](https://user-images.githubusercontent.com/41286936/54403557-6b2f8700-470b-11e9-9f46-1d6dec1a9096.png)
一个是wider_face_train.txt,一个是wider_face_train_bbx_gt.txt，train_bbx_gt文件的边框格式是x1,y1,w,h,我对应的看了下train.txt文件，发现这个格式应该是x1,y1,x2,y2的格式，但是不明白为啥边框数据还带着小数，虽然这个对边框位置感觉影响不大
![train](https://user-images.githubusercontent.com/41286936/54403783-44258500-470c-11e9-8b9d-a70134f83ed3.png)
另一个问题是根据您仓库中gen_12net_data.py中这一句来看
![gen](https://user-images.githubusercontent.com/41286936/54403875-a088a480-470c-11e9-89d3-a8e44d8fc66e.png)，真正的训练标签格式是x1,y1,x2,y2格式。请问您这样理解是否是对的

**Comment by LeslieZhoa** [comment]
Hi @chenwuxing ,对于txt里类型是float我想应该是类型转换时的问题，不过对训练并没有太多影响，对于标签的格式，您的理解是正确的。

**Comment by chenwuxing** [comment]
好的，我对标签格式已经进行了修改，数据也都给加了0-1之间的随机小数，应该是tensorflow一般用的都是float32类型的数据，谢谢您的回复


| |
chenwuxing87
|
|
chenwuxing87@163.com
|
签名由网易邮箱大师定制
在2019年3月17日 19:25，LeslieZhao<notifications@github.com> 写道：

Hi @chenwuxing ,对于txt里类型是float我想应该是类型转换时的问题，不过对训练并没有太多影响，对于标签的格式，您的理解是正确的。
