### ISSUE TITLE
网络推断速度问题

### ISSUE THREAD

**Issue by friedhelm739** [LeslieZhoa/tensorflow-MTCNN#5]
我的pnet训练准确率为93%左右，在图片较大时推断时会生成成千上万个候选框，导致NMS就会花费2s左右。且网络推断速度很慢pnet0.5s左右，gpu是1080ti，已绝望，请问楼主的推断速度是多少呢，有没有注意过候选框数量的问题

**Comment by LeslieZhoa** [comment]
Hi @friedhelm739 速度和你的输入图片大小有关，也与你的阈值设定有关，如果你对pnet的预选框阈值设置很大，它就不会保留那么多，当然代价是准确率降低。
希望对你有所帮助。

**Comment by friedhelm739** [comment]
@LeslieZhoa  请问你训练pnet时生成了多少训练样本呢？我一直在怀疑是我的pnet训练不足，谢谢回答

**Comment by LeslieZhoa** [comment]
@friedhelm739  时间太久远了，我也记不得了，pnet本身就是粗略得到候选框，召回高就可以了。MTCNN就是由粗到细的过程，如果你想cpu实时，建议你resize图片大小，或者使用其他cpu实时的网络。
希望可以帮助到你！

**Comment by friedhelm739** [comment]
@LeslieZhoa 谢谢你的回答~
